const OEM = {
    SUBARU: 'Subaru',
    HONDA: 'Honda',
    HYUNDAI: 'Hyundai',
    TOYOTA: 'Toyota',
    MAZDA: 'Mazda',
    AUDI: 'Audi',
    FORD: 'Ford',
    NISSAN: 'Nissan',
    BMW: 'BMW',
    VW: 'Volkswagen',
    DODGE: 'Dodge',
    CHEVROLET: 'Chevrolet',
}

const TRANSMISSION = {
    MT: { name: 'manual transmission', driveloss: 0 },
    AT: { name: 'automatic transmission', driveloss: 2 },
    AM: { name: 'automated manual', driveloss: 2 },
    CVT: { name: 'continuously variable transmission', driveloss: 2 },
}

const DRIVETRAIN = {

    FWD: { name: 'front wheel drive', driveloss: 17 },
    RWD: { name: 'rear wheel drive', driveloss: 20 },
    AWD: { name: 'all wheel drive', driveloss: 25 },
}

const ENGINE_INDUCTION = {
    T: 'Turbo',
    SC: 'Supercharger',
    NA: 'Naturally Aspirated',
    HYB: 'Hybrid',
}

const CYLINDER_ORIENTATION = {
    I: 'I',
    V: 'V',
    H: 'H',

}

const CARS = {

    CHEVROLET_CORVETTE_1994_NAMT: {
        oem: OEM.CHEVROLET,
        model: 'Corvette',
        year: 1994,
        trim: 'LT1',
        engineType: 'NA',
        trans: 'MT',
        displacement: '5.7',
        cylNum: 8,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 300,
        tq: 340,
        drive: 'RWD',
        weight: 3309,
        image: '1994-Chevrolet-Corvette-ZR1',
        clearance: 5.1,
        wheelbase: 96.2,
        trackWidth: {
            front: 59.6,
            rear: 60.6,
        },

    },
    VW_BEETLE_1960_NAM: {
        oem: OEM.VW,
        model: 'Beetle',
        year: 1960,
        trim: '',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 36,
        drive: 'RWD',
        weight: 1600,
        image: '1960-Volkswagen-Beetle',
        clearance: 6,
        wheelbase: 94.5,
        trackWidth: {
            front: 51.4,
            rear: 49.2,
        },

    },
    VW_GOLF_2015_TAM: {
        oem: OEM.VW,
        model: 'Golf',
        year: 2015,
        trim: 'GTI S',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 210,
        drive: 'FWD',
        weight: 2972,
        image: '2015-Volkswagen-Golf-GTI',
        clearance: 5,
        wheelbase: 103.6,
        trackWidth: {
            front: 60.6,
            rear: 59.7,
        },
    },
    BMW_328_2014_TAM: {
        oem: OEM.BMW,
        model: '3 Series',
        year: 2019,
        trim: '328i',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 240,
        drive: 'RWD',
        weight: 3410,
        image: '2014-BMW-328',
        clearance: 5.5,
        wheelbase: 110.6,
        trackWidth: {
            front: 60.7,
            rear: 62.3,
        },
    },
    DODGE_CHARGER_2014_NAAT: {
        oem: OEM.DODGE,
        model: 'Charger',
        year: 2014,
        trim: 'SXT',
        engineType: 'NA',
        trans: 'AT',
        displacement: '3.6',
        cylNum: 6,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 292,
        drive: 'RWD',
        weight: 3961,
        image: '2014-Dodge-Charger',
        clearance: 5,
        wheelbase: 120.2,
        trackWidth: {
            front: 63.4,
            rear: 63.8,
        },
    },
    FORD_MUSTANG_2019_NAMT: {
        oem: OEM.FORD,
        model: 'Mustang',
        year: 2019,
        trim: 'GT',
        engineType: 'NA',
        trans: 'MT',
        displacement: '5.0',
        cylNum: 8,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 460,
        drive: 'RWD',
        weight: 3705,
        image: '2018-Ford-Mustang-GT',
        clearance: 5,
        wheelbase: 107.1,
        trackWidth: {
            front: 62.3,
            rear: 64.9,
        },
    },
    FORD_FOCUS_2018_TMT: {
        oem: OEM.FORD,
        model: 'Focus',
        year: 2018,
        trim: 'ST',
        engineType: 'T',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 252,
        drive: 'FWD',
        weight: 3223,
        image: '2018-Ford-Focus-ST',
        clearance: 5.5,
        wheelbase: 104.3,
        trackWidth: {
            front: 61.2,
            rear: 60.4,
        },
    },
    FORD_FOCUS_2018_NAAT: {
        oem: OEM.FORD,
        model: 'Focus',
        year: 2018,
        trim: 'Titanium',
        engineType: 'NA',
        trans: 'AT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 160,
        drive: 'FWD',
        weight: 3043,
        image: '2018-Ford-Focus-Titanium',
        clearance: 6.4,
        wheelbase: 104.3,
        trackWidth: {
            front: 61.6,
            rear: 60.6,
        },
    },
    FORD_FIESTA_2018_TMT: {
        oem: OEM.FORD,
        model: 'Fiesta',
        year: 2018,
        trim: 'ST',
        engineType: 'T',
        trans: 'MT',
        displacement: '1.6',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 197,
        tq: 202,
        drive: 'FWD',
        weight: 2720,
        image: '2018-Ford-Fiesta-ST',
        clearance: 6,
        wheelbase: 98,
        trackWidth: {
            front: 57.7,
            rear: 57.7,
        },

    },
    SUBARU_IMPREZA_2016_NACVT: {
        id: 'SUBARU_IMPREZA_2016_NACVT',
        oem: OEM.SUBARU,
        model: 'Impreza',
        year: 2016,
        trim: 'Sport Premium',
        engineType: 'NA',
        engineName: 'FB20',
        trans: 'CVT',
        transGear: 6,
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 148,
        tq: 145,
        drive: 'AWD',
        weight: 3109,
        image: '2016-Subaru-Impreza-Sport',
        wheelbase: 104.1,
        clearance: 5.9,
        trackWidth: {
            front: 59.4,
            rear: 59.6,
        },
        mods: [

            // Power            
            {
                type: 'Airbox',
                category: 'intake',
                manufacturer: "DIY",
                description: "Charcol Filter Delete, Sealed",
                power: 1,
                cost: 0,
            },
            {
                type: 'Filter',
                category: 'intake',
                manufacturer: "Apexi",
                description: "High Flow",
                power: 3,
                cost: 50,
            },
            {
                type: 'Intake',
                category: 'intake',
                manufacturer: "Takeda",
                description: "Hybrid Intake Pipe",
                weight: -2,
                power: 3,
                cost: 200,
            },

            {
                type: 'PCV Air Oil Separator',
                category: 'engine',
                manufacturer: "Crawford",
                description: "Baja Edition - Cleans up engine blow-by",
                weight: 3,
                cost: 200,
            },


            {
                type: 'Breather Catch Can',
                category: 'engine',
                manufacturer: "DIY",
                description: "Cleans up engine blow-by",              
                weight: 2,
                cost: 50,
            },
            {
                type: 'Tune - Stage 1',
                category: 'engine',
                manufacturer: "Throttle Happy",
                description: "Stage 1",
                power: 5,
                cost: 300,
            },
            {
                type: 'Power Blocks',
                category: 'engine',
                manufacturer: "Crawford",
                description: "Intake Runner Extensions",
                power: 5,
                weight: 5,
                cost: 300,
            },
            {
                type: 'Tune - Stage 2',
                category: 'engine',
                manufacturer: "XRT",
                description: "Stage 2",
                power: 10,
                cost: 600,
            },
            {
                type: 'Turbo',
                category: 'engine',
                manufacturer: "AVO",
                description: "Turbo",
                power: 57,
                weight: 97,
                cost: 5000,
            },

            {
                type: 'Axleback',
                category: 'exhaust',
                manufacturer: "Nameless",
                description: 'Single exit 5" muffler and 2.25" piping',
                weight: -10,
                power: 1,
                cost: 150,
            },
            {
                type: 'Front Pipe',
                category: 'exhaust',
                manufacturer: "AVO",
                description: "Catted Stainless 2.5in piping",
                power: 1,
                cost: 350,
            },
            {
                type: 'Midpipe',
                category: 'exhaust',
                manufacturer: "Nameless",
                description: "resonator and 2.25in piping",
                power: 1,
                cost: 500,
            },
            {
                type: 'Engine Headers',
                category: 'exhaust',
                manufacturer: "Inferno Fabrications",
                description: "Equal Length 4-1 catted",
                power: 7,
                weight: -10,
                cost: 700,
            },

            // Drivetrain
            {
                type: 'Engine Pitch Stop',
                category: 'drivetrain',
                manufacturer: "Torque Solutions",
                description: "75A",
                drivetrain: 1,
                cost: 70,
            },
            {
                type: 'Transmission Mount',
                category: 'drivetrain',
                manufacturer: "CKE SSP",
                description: "75A",
                drivetrain: 1,
                cost: 30,
            },
            {
                type: 'Driveshaft Carrier',
                category: 'drivetrain',
                manufacturer: "Torque Solution",
                description: "Aluminum Billet",
                drivetrain: 0.5,
                cost: 35,
            },
            {
                type: 'Differential Lockdown',
                category: 'drivetrain',
                manufacturer: "Perrin",
                description: "2pc Billet, 4pc 75A",
                drivetrain: 1.5,
                cost: 115,
            },
            {
                type: 'Fluid Damper',
                category: 'drivetrain',
                manufacturer: "Fluid Damper",
                description: "Silicone vibration damper",
                drivetrain: 1.5,
                weight: 2,
                cost: 400,
            },
            {
                type: 'Engine Mounts',
                category: 'drivetrain',
                manufacturer: "Perrin",
                description: "75A",
                drivetrain: 1,
                cost: 300,
            },
            {
                type: 'Carbon Driveshaft',
                category: 'drivetrain',
                manufacturer: "Driveshaft Shop",
                description: "Lightweight Driveshaft",
                drivetrain: 2,
                weight: -12,
                cost: 1100,
            },
            {
                type: 'Front Wheel Drive',
                category: 'drivetrain',
                manufacturer: "OEM",
                description: "Disable AWD via fuse",
                drivetrain: 5,
                handling: -2,
                cost: 0,
            },

            //
            // Handling
            //
            {
                type: 'Steering Lockdown',
                category: 'handling',
                manufacturer: "Torque Solutions",
                description: 'Tightens Steering Response',
                handling: 1,
                cost: 50,
            },
            {
                type: 'Draw Stiffener',
                category: 'handling',
                manufacturer: "STI",
                description: 'Preloaded Front Chassis Stiffener',
                handling: 1,
                weight: 1,
                cost: 270,
            },
            {
                type: 'Front Strut Bar',
                category: 'handling',
                manufacturer: "STI",
                description: 'Flexible',
                handling: 1,
                weight: 5,
                cost: 300,
            },
            {
                type: 'Rear Strut Bar',
                category: 'handling',
                manufacturer: "Unknown",
                description: 'Attaches across rear struts',
                handling: 1,                
                weight: 6,
                cost: 130,
            },
            {
                type: 'Traction Bars',
                category: 'handling',
                manufacturer: "TB Performance",
                description: 'Beefed up Tubular steel front suspension suport brackets',
                handling: 1,
                weight: 2,
                cost: 150,
            },
            {
                type: 'Rear Subframe Brace',
                category: 'handling',
                manufacturer: "Kein",
                description: 'Tubular steel - ties rear subframe bolts',
                handling: 1,
                weight: 5,
                cost: 100,
            },


            // Suspension
            {
                type: 'Rear Sway Bar 20mm',
                category: 'suspension',
                manufacturer: "Subaru",
                description: '20mm',
                handling: 1,
                cost: 100,
            },

            {
                type: 'Rear Sway Bar 22mm',
                category: 'suspension',
                manufacturer: "Whiteline",
                description: '22mm adjustable',
                handling: 1.5,
                cost: 240,
            },
            {
                type: 'Front Sway Bar',
                category: 'suspension',
                manufacturer: "Subaru",
                description: '24mm XV Crosstrek',
                handling: 1,
                cost: 100,
            },
            {
                type: 'Lowering Springs',
                category: 'suspension',
                manufacturer: "RS-R",
                description: "Down Sus",
                handling: 2,
                weight: -5,
                cost: 300,
            },
            {
                type: 'Coilovers',
                category: 'suspension',
                manufacturer: "Fortune Auto",
                description: "500 Series - Radial Bearing 8k Springs",
                handling: 4,
                weight: -15,
                drivetrain: 1,
                cost: 1500,
            },
            {
                type: 'Lower',
                category: 'suspension',
                manufacturer: "None",
                description: 'Lower 1 inch',
                height: 1,
                cost: 0,
            },
            {
                type: 'Trailing Links',
                category: 'suspension',
                manufacturer: "Megan Racing",
                description: 'Pillow ball bush, tubular steel',
                handling: 1,
                weight: 2,
                drivetrain: 0.5,
                cost: 120,
            },
            {
                type: 'Rear Lower Control Arms',
                category: 'suspension',
                manufacturer: "Super Pro",
                description: '75A Poly Bushing, Steel, adj. camber',
                handling: 1,
                drivetrain: 0.5,
                cost: 250,
            },
            {
                type: 'Rear Toe Arms',
                category: 'suspension',
                manufacturer: "Super Pro",
                description: '75A Poly Bushing, adj. toe',
                handling: 0.5,
                weight: 2,
                cost: 150,
            },
            {
                type: 'Rear Subframe Buhsings',
                category: 'suspension',
                manufacturer: "Whiteline",
                description: '8 subframe bushing inserts',
                handling: 1,
                drivetrain: 1,
                cost: 50,
            },

            // wheels
            {
                type: 'Wheels',
                category: 'wheels',
                manufacturer: "Enkei",
                description: "Subaru STI 15 spoke",
                handling: 1,
                drivetrain: 0.5,
                brake: 1,
                weight: -28,
                cost: 1000,
            },

            {
                type: 'Tires',
                category: 'wheels',
                manufacturer: "Firestone",
                description: "Firehawk Indy 500 UHP",
                brake: 1,
                handling: 1,
                cost: 600,
            },
            {
                type: 'Front Wheel Spacers 15mm',
                category: 'wheels',
                manufacturer: "",
                description: '15mm wheel spacers ',
                trackWidth: {
                    'front': 0.6,
                },
                weight: 5,
                cost: 100,
            },
            {
                type: 'Front Wheel Spacers 20mm',
                category: 'wheels',
                manufacturer: "",
                description: '20mm wheel spacers ',
                trackWidth: {
                    'front': 0.79,
                },
                weight: 5,
                cost: 100,
            },
            {
                type: 'Front Wheel Spacers 25mm',
                category: 'wheels',
                manufacturer: "",
                description: '25mm wheel spacers ',
                trackWidth: {
                    'front': 1,
                },
                weight: 5,
                cost: 100,
            },
            {
                type: 'Rear Wheel Spacers 15mm',
                category: 'wheels',
                manufacturer: "",
                description: '15mm wheel spacers ',
                trackWidth: {
                    'rear': 0.6,
                },
                weight: 5,
                cost: 100,
            },
            {
                type: 'Rear Wheel Spacers 20mm',
                category: 'wheels',
                manufacturer: "",
                description: '20mm wheel spacers ',
                trackWidth: {
                    'rear': 0.79,
                },
                weight: 5,
                cost: 100,
            },

            {
                type: 'Rear Wheel Spacers 25mm',
                category: 'wheels',
                manufacturer: "",
                description: '25mm wheel spacers ',
                trackWidth: {
                    'rear': 1,
                },
                weight: 5,
                cost: 100,
            },



            // Braking 
            {
                type: 'DOT 4 Fluid',
                category: 'brake',
                manufacturer: 'Pentosin',
                description: 'High boiling point',
                brake: 1,
                cost: 15,
            },
            {
                type: 'Master Cylinder Brace',
                category: 'brake',
                manufacturer: 'Torque Solutions',
                description: 'firmer braking',
                brake: 1,
                cost: 100,
            },
            {
                type: 'Front Pads',
                category: 'brake',
                manufacturer: 'Project Mu',
                description: 'B-spec 500C',
                brake: 1.5,
                cost: 100,
            },
            {
                type: 'Rear Pads',
                category: 'brake',
                manufacturer: 'Hawk',
                description: 'HPS 5.0 550C',
                brake: 1,
                cost: 100,
            },
            {
                type: 'Front Rotors',
                category: 'brake',
                manufacturer: 'KNS/DBA',
                description: 'Oversized, High Carbon',
                brake: 2,
                weight: 5,
                cost: 300,
            },
            {
                type: 'Stainless Brake Lines',
                category: 'brake',
                manufacturer: 'Goodridge',
                description: 'firmer braking',
                brake: 1,
                cost: 100,
            },


            //
            // Weight
            //
            {
                type: 'Trunk Delete',
                category: 'weight',
                manufacturer: "DIY",
                description: 'Removed spare tire, tools, Trunk liners',
                weight: -40,
                cost: 0,
                utility: -1
            },
            {
                type: 'Trunk Delete 2',
                category: 'weight',
                manufacturer: "DIY",
                description: 'Removed rear seat belts and additional paneling',
                weight: -17,
                cost: 0,
                utility: -1
            },
            {
                type: 'Rear Seat Delete',
                category: 'weight',
                manufacturer: "DIY",
                description: 'Removed rear seats',
                weight: -35 ,
                cost: 0,
                utility: -1
            },
            {
                type: 'Rear Door Card Delete',
                category: 'weight',
                manufacturer: "DIY",
                description: 'Removed rear door cards and speakers',
                weight: -11,
                cost: 0,
                utility: -2
            },
            {
                type: 'Passenger Seat Delete',
                category: 'weight',
                manufacturer: "DIY",
                description: 'Removed passenger seat',
                weight: -40,
                cost: 0,
                utility: -1
            },
            {
                type: 'Light Weight Battery',
                category: 'weight',
                manufacturer: "Braille",
                description: 'Lithum Polymer',
                weight: -30,
                cost: 1500,                
            },

            {
                type: 'BRZ EQ Pack',
                category: 'weight',
                manufacturer: "DIY",
                description: 'BRZ Parity',
                weight: -347,
                power: 57,
                height: 1,
                drivetrain: 5,
                trackWidth: {
                    front: 1.6,
                    rear: 1.6,
                },
                cost: 0,
            },



        ]
    },
    SUBARU_STI_2008_TMT: {
        oem: OEM.SUBARU,
        model: 'WRX',
        year: 2008,
        trim: 'STI',
        engineType: 'T',
        engineName: 'EJ257',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 305,
        drive: 'AWD',
        weight: 3395,
        image: '2008-Subaru-WRX-STI',
        wheelbase: 103.3,
        clearance: 6.1,
        trackWidth: {
            front: 60.2,
            rear: 60.6,
        },
    },
    SUBARU_BRZ_2014_NAMT: {
        oem: OEM.SUBARU,
        model: 'BRZ',
        year: 2014,
        trim: 'Premium',
        engineType: 'NA',
        engineName: 'FA20',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 205,
        tq: 151,
        drive: 'RWD',
        weight: 2762,
        image: '2014-Subaru-BRZ',
        clearance: 4.9,
        wheelbase: 101.2,
        trackWidth: {
            front: 59.8,
            rear: 60.6,
        }
    },
    HONDA_HRV_2020_NAAT: {
        oem: OEM.HONDA,
        model: 'HR-V',
        year: 2020,
        trim: 'Sport',
        engineType: 'NA',
        trans: 'AT',
        displacement: '1.8',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 141,
        drive: 'FWD',
        weight: 3096,
        image: '2020-Honda-HRV-Sport',
        clearance: 6.7,
        wheelbase: 102.8,
        trackWidth: {
            front: 60.5,
            rear: 60.6,
        }
    },
    HONDA_ACCORD_2019_TAT: {
        oem: OEM.HONDA,
        model: 'Accord',
        year: 2018,
        trim: 'Sport',
        engineType: 'T',
        trans: 'AT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 250,
        drive: 'FWD',
        weight: 3377,
        image: '2019-Honda-Accord-Sport',
        clearance: 6.7,
        wheelbase: 111.4,
        trackWidth: {
            front: 63,
            rear: 63.4,
        }
    },
    HONDA_FIT_2016_NAAT: {
        oem: OEM.HONDA,
        model: 'Fit',
        year: 2016,
        trim: 'EX-L',
        engineType: 'NA',
        trans: 'AT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 130,
        drive: 'FWD',
        weight: 2642,
        image: '2016-Honda-Fit-EX-L',
        clearance: 4.4,
        wheelbase: 99.6,
        trackWidth: {
            front: 58.3,
            rear: 58,
        }
    },
    TOYOTA_CAMRY_2006_NAAT: {
        oem: OEM.TOYOTA,
        model: 'Camry',
        year: 2006,
        trim: 'LE',
        engineType: 'NA',
        trans: 'AT',
        displacement: '2.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 154,
        drive: 'FWD',
        weight: 3108,
        image: '2006-Toyota-Camry-LE',
        clearance: 5.5,
        wheelbase: 107.1,
        trackWidth: {
            front: 60.8,
            rear: 60.4,
        }
    },
    TOYOTA_MATRIX_2014_NAMT: {
        oem: OEM.TOYOTA,
        model: 'Matrix',
        year: 2013,
        trim: 'XRS',
        engineType: 'NA',
        engineName: '2ZZ-GE',
        trans: 'MT',
        displacement: '2.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 158,
        drive: 'AWD',
        weight: 3274,
        image: '2014-Toyota-Matrix-XRS',
        clearance: 5.8,
        wheelbase: 102.4,
        trackWidth: {
            front: 59.8,
            rear: 59.9,
        }
    },
    TOYOTA_YARIS_2012_NAAT: {
        oem: OEM.TOYOTA,
        model: 'Yaris',
        year: 2012,
        trim: 'LE',
        engineType: 'NA',
        trans: 'AT',
        displacement: '1.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 106,
        drive: 'FWD',
        weight: 2315,
        image: '2012-Toyota-Yaris',
        wheelbase: 98.8,
        clearance: 5.8,
        trackWidth: {
            front: 58.5,
            rear: 57.9,
        },
    },
    MAZDA_3_2008_NAMT: {
        oem: OEM.MAZDA,
        model: '3',
        year: 2008,
        trim: 'S Touring',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.3',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 156,
        drive: 'FWD',
        weight: 2959,
        image: '2008-Mazda-3',
        clearance: 4.8,
        wheelbase: 103.9,
        trackWidth: {
            front: 60.2,
            rear: 59.6,
        },
    },
    AUDI_A3_2008_TAM: {
        oem: OEM.AUDI,
        model: 'A3',
        year: 2013,
        trim: 'Premium Plus Sport',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 200,
        drive: 'FWD',
        weight: 3296,
        image: '2008-Audi-A3',
        wheelbase: 101.5,
        clearance: 6.3,
        trackWidth: {
            front: 60.5,
            rear: 59.3,
        },

    },
    HONDA_CIVIC_1992_NAMT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 1992,
        trim: 'SI',
        engineType: 'NA',
        trans: 'MT',
        displacement: '1.6',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 125,
        drive: 'FWD',
        weight: 2326,
        image: '1992-Honda-Civic-SI',
        clearance: 5.9,
        wheelbase: 101.3,
        trackWidth: {
            front: 58.1,
            rear: 57.7,
        },
    },
    HONDA_CIVIC_2019_TAT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 2019,
        trim: 'Sport Touring',
        engineType: 'T',
        trans: 'AT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 180,
        drive: 'FWD',
        weight: 3010,
        image: '2019-Honda-Civic-Sport',
        clearance: 6,
        wheelbase: 106.3,
        trackWidth: {
            front: 60.9,
            rear: 61.5,
        },
    },
    HONDA_CIVIC_2019_TMT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 2019,
        trim: 'SI',
        engineType: 'T',
        trans: 'MT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 205,
        tq: 196,
        drive: 'FWD',
        weight: 2906,
        image: '2019-Honda-Civic-SI',
        clearance: 6,
        wheelbase: 106.3,
        trackWidth: {
            front: 60.5,
            rear: 61.2,
        },
    },
    NISSAN_PICKUP_1993_NAMT: {
        oem: OEM.NISSAN,
        model: 'Pickup',
        year: 1993,
        trim: 'Crew Cab',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 134,
        drive: 'RWD',
        weight: 3175,
        image: '1993-Nissan-Pickup',
        clearance: 6.7,
        wheelbase: 116.1,
        trackWidth: {
            front: 65,
            rear: 66.5,
        },

    },
    NISSAN_350Z_2009_NAMT: {
        oem: OEM.NISSAN,
        model: '350Z',
        year: 2009,
        trim: 'Touring',
        engineType: 'NA',
        engineName: 'VQ35DE',
        trans: 'MT',
        displacement: '3.5',
        cylNum: 6,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 306,
        drive: 'RWD',
        weight: 3602,
        image: '2009-Nissan-350z',
        clearance: 4.7,
        wheelbase: 104.3,
        trackWidth: {
            front: 60.5,
            rear: 60.6,
        },

    },
    TOYOTA_PRIUS_2017: {
        oem: OEM.TOYOTA,
        model: 'Prius',
        year: 2017,
        trim: 'Prime',
        engineType: 'HYB',
        trans: 'CVT',
        displacement: '1.8',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 121,
        drive: 'FWD',
        weight: 3050,
        image: '2017-Toyota-Prius-Prime',
        clearance: 4.8,
        wheelbase: 106.3,
        trackWidth: {
            front: 60.2,
            rear: 60.6,
        },
        mods: [
            {
                type: 'Interior Delete',
                manufacturer: "DIY",
                description: 'Gutted',
                weight: -250,
                cost: 0,
                utility: -2
            },
        ]
    },
    HYUNDAI_VELOSTER_2021: {
        oem: OEM.HYUNDAI,
        model: 'Veloster',
        year: 2021,
        trim: 'Premium',
        engineType: 'NA',
        trans: 'AT',
        transGear: 6,
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 147,
        tq: 132,
        drive: 'FWD',
        weight: 2855,
        image: '2021-Hyundai-Veloster-Premium',
        clearance: 5.6,
        wheelbase: 104.3,
        trackWidth: {
            front: 61,
            rear: 61.5,
        },
        mods: [
            {
                type: 'Interior Delete',
                manufacturer: "DIY",
                description: 'Gutted',
                weight: -250,
                cost: 0,
                utility: -2
            },
        ]
    }

}