const OEM = {
    SUBARU: 'Subaru',
    HONDA: 'Honda',
    TOYOTA: 'Toyota',
    MAZDA: 'Mazda',
    AUDI: 'Audi',
    FORD: 'Ford',
    NISSAN: 'Nissan',
    BMW: 'BMW',
    VW: 'Volkswagen',
    DODGE: 'Dodge',
    CHEVROLET: 'Chevrolet',
}

const TRANSMISSION = {
    MT: 'manual transmission',
    AT: 'automatic transmission',
    AM: 'automated manual',
    CVT: 'continuously variable transmission',    
}

const DRIVETRAIN = {
    AWD: 'all wheel drive',
    FWD: 'front wheel drive',
    RWD: 'rear wheel drive',
}

const ENGINE_INDUCTION = {
    T: 'Turbo',
    SC: 'Supercharger',
    NA: 'Naturally Aspirated',
    HYB: 'Hybrid',
}

const CYLINDER_ORIENTATION = {
    I: 'I',
    V: 'V',
    H: 'H',

}

const CARS = {

    CHEVROLET_CORVETTE_1994_NAMT: {
        oem: OEM.CHEVROLET,
        model: 'Corvette',
        year: 1994,
        trim: 'LT1',
        engineType: 'NA',
        trans: 'MT',
        displacement: '5.7',
        cylNum: 8,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 300,
        tq: 340,
        drive: 'RWD',
        weight: 3309,
        image: '1994-Chevrolet-Corvette-ZR1'
    },
    VW_BEETLE_1960_NAM: {
        oem: OEM.VW,
        model: 'Beetle',
        year: 1960,
        trim: '',
        engineType: 'NA',
        trans: 'M',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 36,
        drive: 'RWD',
        weight: 1600,
        image: '1960-Volkswagen-Beetle',
    },
    VW_GOLF_2015_TAM: {
        oem: OEM.VW,
        model: 'Golf',
        year: 2015,
        trim: 'GTI S',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 210,
        drive: 'FWD',
        weight: 2972,
        image: '2015-Volkswagen-Golf-GTI',
    },
    BMW_328_2014_TAM: {
        oem: OEM.BMW,
        model: '3 Series',
        year: 2019,
        trim: '328i',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 240,
        drive: 'RWD',
        weight: 3410,
        image: '2014-BMW-328'
    },
    DODGE_CHARGER_2014_NAAT: {
        oem: OEM.DODGE,
        model: 'Charger',
        year: 2014,
        trim: 'SXT',
        engineType: 'NA',
        trans: 'AT',
        displacement: '3.6',
        cylNum: 6,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 292,
        drive: 'RWD',
        weight: 4000,
        image: '2014-Dodge-Charger'
    },
    FORD_MUSTANG_2019_NAMT: {
        oem: OEM.FORD,
        model: 'Mustang',
        year: 2019,
        trim: 'GT',
        engineType: 'NA',
        trans: 'MT',
        displacement: '5.0',
        cylNum: 8,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 460,
        drive: 'RWD',
        weight: 3705,
        image: '2018-Ford-Mustang-GT',
    },
    FORD_FOCUS_2018_TMT: {
        oem: OEM.FORD,
        model: 'Focus',
        year: 2018,
        trim: 'ST',
        engineType: 'T',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 252,
        drive: 'FWD',
        weight: 3223,
        image: '2018-Ford-Focus-ST',
    },    
    FORD_FOCUS_2018_NAAT: {
        oem: OEM.FORD,
        model: 'Focus',
        year: 2018,
        trim: 'Titanium',
        engineType: 'NA',
        trans: 'AT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 160,
        drive: 'FWD',
        weight: 3043,
        image: '2018-Ford-Focus-Titanium',
    },
    FORD_FIESTA_2018_TMT: {
        oem: OEM.FORD,
        model: 'Fiesta',
        year: 2018,
        trim: 'ST',
        engineType: 'T',
        trans: 'MT',
        displacement: '1.6',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 197,
        tq: 202,
        drive: 'FWD',
        weight: 3223,
        image: '2018-Ford-Fiesta-ST',
        
    },
    SUBARU_IMPREZA_2016_NACVT: {
        oem: OEM.SUBARU,
        model: 'Impreza',
        year: 2016,
        trim: 'Sport Premium',
        engineType: 'NA',
        trans: 'CVT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 148,
        tq: 145,
        drive: 'AWD',
        weight: 3109,
        image: '2016-Subaru-Impreza-Sport',
        mods: [            
            {
                'Tune': {
                    manufacturer: "Throttle Happy",
                    description: "Rev 5A 91/93 Ocatane",
                    power: 5,
                },
            },
            {
                'Engine Pitch Stop': {
                    manufacturer: "Torque Solutions",
                    description: "75A",
                    power: 1,
                },
            },
            // {
            //     'Power Billet Blocks': {
            //         manufacturer: "Crawford",
            //         description: "Intake Runner Extensions",
            //         power: 3,
            //     },
            // },
            // {
            //     'Filter': {
            //         manufacturer: "Apexi",
            //         description: "high flow filter",
            //         power: 1,
            //     },
            // },
            {
                'Airbox': {
                    manufacturer: "DIY",
                    description: "Throated airbox",
                    power: 1,
                },
            },
            // {
            //     'Differential Lockdown': {
            //         manufacturer: "Perrin",
            //         description: "",
            //         power: 1,
            //         handling: 1
            //     },
            // },
            // {
            //     'Coilovers': {
            //         manufacturer: "Fortune Auto",
            //         description: "500 Series",                    
            //         handling: 4,
            //         power: 2,
            //         weight: 15,
            //     },
            // },
            {
                'Wheels': {
                    manufacturer: "Enkei",
                    description: "Subaru STI 15 spoke",
                    handling: 2,
                    weight: 28,
                },
            },
            {
                'Exhaust': {
                    manufacturer: "Nameless",
                    description: "5inch",
                    weight: 5,
                    power: 1,
                },
            },
            {
                'Steering Lockdown': {
                    manufacturer: "Torque Solutions",
                    description: '',
                    handling: 1,
                }
            },
            {
                'Front Sway Bar': {
                    manufacturer: "Subaru",
                    description: '24mm XV Crosstrek',
                    handling: 1,
                }
            },
            {
                'Rear Sway Bar': {
                    manufacturer: "Whiteline",
                    description: '22mm adjustable',
                    handling: 1.5,
                }
            },
            // {
            //     'Rear Seat Delete': {
            //         manufacturer: "DIY",
            //         description: 'Removed rear seats',
            //         weight: 75,
            //     }
            // },
            // {
            //     'Trunk Delete': {
            //         manufacturer: "DIY",
            //         description: 'Removed Trunk Interior',
            //         weight: 40,
            //     }
            // },
        ]
    },
    SUBARU_STI_2008_TMT: {
        oem: OEM.SUBARU,
        model: 'WRX',
        year: 2008,
        trim: 'STI',
        engineType: 'T',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 305,
        drive: 'AWD',
        weight: 3395,
        image: '2008-Subaru-WRX-STI',
    },
    SUBARU_BRZ_2014_NAMT: {
        oem: OEM.SUBARU,
        model: 'BRZ',
        year: 2014,
        trim: 'Premium',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.H,
        hp: 205,
        tq: 151,
        drive: 'RWD',
        weight: 2762,
        image: '2014-Subaru-BRZ',
    },
    
    HONDA_ACCORD_2019_TAT: {
        oem: OEM.HONDA,
        model: 'Accord',
        year: 2018,
        trim: 'Sport',
        engineType: 'T',
        trans: 'AT',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 250,
        drive: 'FWD',
        weight: 3377,
        image: '2019-Honda-Accord-Sport',
    },
    HONDA_FIT_2016_NAAT: {
        oem: OEM.HONDA,
        model: 'Fit',
        year: 2016,
        trim: 'EX-L',
        engineType: 'NA',
        trans: 'AT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 130,
        drive: 'FWD',
        weight: 2642,
        image: '2016-Honda-Fit-EX-L',
    },
    TOYOTA_CAMRY_2006_NAAT: {
        oem: OEM.TOYOTA,
        model: 'Camry',
        year: 2006,
        trim: 'LE',
        engineType: 'NA',
        trans: 'AT',
        displacement: '2.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 154,
        drive: 'FWD',
        weight: 3108,
        image: '2006-Toyota-Camry-LE',
    },
    TOYOTA_MATRIX_2014_NAMT: {
        oem: OEM.TOYOTA,
        model: 'Matrix',
        year: 2013,
        trim: 'XRS',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 158,
        drive: 'AWD',
        weight: 3274,
        image: '2014-Toyota-Matrix-XRS',
    },
    TOYOTA_YARIS_2012_NAAT: {
        oem: OEM.TOYOTA,
        model: 'Yaris',
        year: 2012,
        trim: 'LE',
        engineType: 'NA',
        trans: 'AT',
        displacement: '1.4',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 106,
        drive: 'FWD',
        weight: 2315,
        image: '2012-Toyota-Yaris',
    },
    MAZDA_3_2008_NAMT: {
        oem: OEM.MAZDA,
        model: '3',
        year: 2008,
        trim: 'S Touring',
        engineType: 'NA',
        trans: 'MT',
        displacement: '2.3',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 156,
        drive: 'FWD',
        weight: 2959,
        image: '2008-Mazda-3',
    },
    AUDI_A3_2008_TAM: {
        oem: OEM.AUDI,
        model: 'A3',
        year: 2013,
        trim: 'Premium Plus Sport',
        engineType: 'T',
        trans: 'AM',
        displacement: '2.0',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 200,
        drive: 'FWD',
        weight: 3296,
        image: '2008-Audi-A3',
    },
    HONDA_CIVIC_1992_NAMT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 1992,
        trim: 'SI',
        engineType: 'NA',
        trans: 'MT',
        displacement: '1.6',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 125,
        drive: 'FWD',
        weight: 2326,
        image: '1992-Honda-Civic-SI',
    },
    HONDA_CIVIC_2019_TAT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 2019,
        trim: 'Sport Touring',
        engineType: 'T',
        trans: 'AT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 180,
        drive: 'FWD',
        weight: 3010,
        image: '2019-Honda-Civic-Sport',
    },
    HONDA_CIVIC_2019_TMT: {
        oem: OEM.HONDA,
        model: 'Civic',
        year: 2019,
        trim: 'SI',
        engineType: 'T',
        trans: 'MT',
        displacement: '1.5',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 205,
        tq: 196,
        drive: 'FWD',
        weight: 2906,
        image: '2019-Honda-Civic-SI',
    },
    NISSAN_350Z_2009_NAMT: {
        oem: OEM.NISSAN,
        model: '350Z',
        year: 2009,
        trim: 'Touring',
        engineType: 'NA',
        trans: 'MT',
        displacement: '3.5',
        cylNum: 6,
        cylOr: CYLINDER_ORIENTATION.V,
        hp: 306,
        drive: 'RWD',
        weight: 3602,
        image: '2009-Nissan-350z',

    },
    TOYOTA_PRIUS_2017: {
        oem: OEM.TOYOTA,
        model: 'Prius',
        year: 2017,
        trim: 'Prime',
        engineType: 'HYB',
        trans: 'CVT',
        displacement: '1.8',
        cylNum: 4,
        cylOr: CYLINDER_ORIENTATION.I,
        hp: 121,
        drive: 'FWD',
        weight: 3050,
        image: '2017-Toyota-Prius-Prime'
    }


}